# Basic Information
title: Mingqi Liu
position: Postdoc
affiliation: École Normale Supérieure - PSL
affiliation_link: https://www.ens.psl.eu/
affiliation_logo: https://www.ens.psl.eu/sites/default/files/logo_ens_psl_en_png.png
email: liumq12@outlook.com

# Search Engine Optimization (SEO)
keywords: mingqi liu, geodynamics, earthquake physics, numerical modeling, planetary tectonics, lithospheric dynamics, fault mechanics
canonical: https://liumq12.github.io
description: Mingqi Liu is a postdoctoral researcher at ENS-PSL working on geodynamics, earthquake physics, numerical modeling, and planetary tectonics.

# Template Options
enable_last_update: true   # Enable to display the last updated timestamp

# Links
link_type: icon # Options: text or icon
google_scholar: https://scholar.google.com/citations?user=kEc2UMgAAAAJ&hl=en
github_link: https://github.com/liumq12
orcid: https://orcid.org/0000-0003-4488-4824
researchgate: https://www.researchgate.net/profile/Mingqi-Liu-10
# linkedin: https://www.linkedin.com/in/mingqi-liu/ # Example placeholder
# twitter: https://twitter.com/mingqi_liu # Example placeholder

# Images
avatar: ../assets/img/Photo_website.JPG

# Footnotes
footnote: Feel free to use the source code for my website.
footnote_link: https://github.com/liumq12/liumq12.github.io

# Analytics
# Remove the following lines if you fork this project to avoid analytics being recorded in my accounts.
# clustrmaps_id: CJD8XwsJhSyQ6sbsU-Gw0cNcUlbah7KW3xvHN2QlwW0

# Exclude Files
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
